server:
  port: 20000
spring:
  main:
    web-application-type: reactive # 防止与 web-starter 冲突
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes: # 路由设置
        - id: user-service #路由的 ID，程序员自己写,要求唯一
          # 服务地址
          uri: lb://userService
          predicates: #断言,路径相匹配的进行路由
            - Path=/user/**
        - id: video-service
          uri: lb://videoService
          predicates:
            - Path=/video/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.172.220:3306/qny?serverTimezone=Asia/Shanghai
    username: root
    password: centos7.6@LiuHuan
  redis:
    host: 101.43.172.220
    port: 6379
    password: 123456
  config:
    name: gatewayService

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml