server:
  port: 10002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qny?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 101.43.172.220
    port: 6379
    password: 123456
  application:
    name: videoService
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印


